// Edge Function용 PDF 라이브러리 번들 (버전 고정, 외부 네트워크 없이 배포·로컬 실행이 같도록)
// - pdf-lib 1.17.1 (MIT): PDF 구조 읽기·쓰기 — 민감정보 글자 제거와 보호본 생성
// - unpdf 1.8.1 (MIT, 내부 pdf.js는 Apache-2.0): 보호본 검증용 텍스트 추출 (독립 구현으로 다시 읽어 원문이 남지 않았는지 확인)
// 다시 만들기: node scripts/vendor-pdf.mjs
import { build } from 'esbuild';
import fs from 'node:fs';

const out = 'supabase/functions/_shared/vendor';
const pkg = (name) => JSON.parse(fs.readFileSync(`node_modules/${name}/package.json`, 'utf8')).version;
const targets = [
  { name: 'pdf-lib', file: 'pdf-lib.js', exports: 'export { PDFArray, PDFDict, PDFDocument, PDFName, PDFNumber, PDFRawStream, PDFRef, PDFStream, PDFString, PDFHexString, PDFContentStream, decodePDFRawStream } from "pdf-lib";' },
  { name: 'unpdf', file: 'unpdf.js', exports: 'export { extractText, getDocumentProxy } from "unpdf";' },
];
for (const t of targets) {
  await build({
    stdin: { contents: t.exports, resolveDir: process.cwd(), loader: 'js' },
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    minify: true,
    legalComments: 'eof',
    outfile: `${out}/${t.file}`,
    banner: { js: `// ${t.name}@${pkg(t.name)} — generated by scripts/vendor-pdf.mjs. Do not edit.` },
    logLevel: 'warning',
  });
}
fs.writeFileSync(`${out}/pdf-lib.d.ts`, `export { PDFArray, PDFDict, PDFDocument, PDFName, PDFNumber, PDFRawStream, PDFRef, PDFStream, PDFString, PDFHexString, PDFContentStream, decodePDFRawStream } from 'pdf-lib';\n`);
fs.writeFileSync(`${out}/unpdf.d.ts`, `export { extractText, getDocumentProxy } from 'unpdf';\n`);
console.log('vendored', targets.map((t) => `${t.name}@${pkg(t.name)}`).join(', '));
