// Edge Function용 PACTO 도메인 번들 — 알림 계획을 앱 화면과 서버(푸시 발송)가 같은 코드로 계산하도록
// 원본: src/domain/*.ts, src/data/supabase/rowMapping.ts (앱 코드가 기준. 번들은 생성물이라 직접 고치지 않는다)
// 다시 만들기: node scripts/vendor-domain.mjs  (src/domain을 고친 뒤 — 테스트가 원본과 번들이 어긋나면 실패한다)
import { build } from 'esbuild';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

export const OUT = 'supabase/functions/_shared/vendor/pacto-domain.js';
const ENTRY = `
export {
  planNotifications, getEffectiveNotificationPreferences, normalizeCategoryPrefs, isValidTimeOfDay, isValidTimeZone,
  NOTIFICATION_CATEGORIES, PLAN_WINDOW_DAYS,
} from './src/domain/notifications';
export { toRecord, CONTRACT_SELECT } from './src/data/supabase/rowMapping';
`;

/** 번들에 들어가는 원본 파일들의 해시 — 원본이 바뀌었는데 번들을 다시 만들지 않으면 테스트가 알려준다 */
export function sourceHash(files) {
  const h = crypto.createHash('sha256');
  for (const f of [...files].sort()) h.update(f).update('\0').update(fs.readFileSync(f)).update('\0');
  return h.digest('hex').slice(0, 16);
}

async function main() {
  const result = await build({
    stdin: { contents: ENTRY, resolveDir: process.cwd(), loader: 'ts' },
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    tsconfig: 'tsconfig.json',
    metafile: true,
    minify: true,
    write: false,
    legalComments: 'eof',
    logLevel: 'warning',
  });
  const inputs = Object.keys(result.metafile.inputs).filter((f) => f.startsWith('src/'));
  const hash = sourceHash(inputs);
  const banner = `// PACTO domain bundle — generated by scripts/vendor-domain.mjs. Do not edit.\n// source-hash: ${hash}\n// sources: ${inputs.sort().join(',')}\n`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, banner + result.outputFiles[0].text);
  console.log(`wrote ${OUT} (${inputs.length} sources, hash ${hash})`);
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
