// Edge Function용 PDF 라이브러리 번들 (버전 고정, 외부 네트워크 없이 배포·로컬 실행이 같도록)
// - pdf-lib 1.17.1 (MIT): PDF 구조 읽기·쓰기 — 민감정보 글자 제거와 보호본 생성 (+ 표준 14 글꼴 글자 너비: @pdf-lib/standard-fonts, MIT)
// - unpdf 1.8.1 (MIT, 내부 pdf.js는 Apache-2.0): 보호본 검증용 텍스트 추출 (독립 구현으로 다시 읽어 원문이 남지 않았는지 확인)
// - 한글 CMap (pdfjs-dist 6.1.200의 cmaps/, Adobe BSD-3 라이선스): 미리 정의된 한글 인코딩(UniKS-UCS2-H, KSCms-UHC-H 등) 글꼴 해석·검증용
//   (Supabase 배포는 import한 파일만 올라가므로 데이터를 모듈 안에 넣는다)
// 다시 만들기: node scripts/vendor-pdf.mjs
import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const out = 'supabase/functions/_shared/vendor';
const pkg = (name) => JSON.parse(fs.readFileSync(`node_modules/${name}/package.json`, 'utf8')).version;
const targets = [
  { name: 'pdf-lib', file: 'pdf-lib.js', exports: 'export { PDFArray, PDFDict, PDFDocument, PDFName, PDFNumber, PDFRawStream, PDFRef, PDFStream, PDFString, PDFHexString, PDFContentStream, decodePDFRawStream } from "pdf-lib"; export { Font as StandardFontMetrics, Encodings as StandardEncodings } from "@pdf-lib/standard-fonts";' },
  { name: 'unpdf', file: 'unpdf.js', exports: 'export { extractText, getDocumentProxy } from "unpdf";' },
];
for (const t of targets) {
  await build({
    stdin: { contents: t.exports, resolveDir: process.cwd(), loader: 'js' },
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    minify: true,
    legalComments: 'eof',
    outfile: `${out}/${t.file}`,
    banner: { js: `// ${t.name}@${pkg(t.name)} — generated by scripts/vendor-pdf.mjs. Do not edit.` },
    logLevel: 'warning',
  });
}
fs.writeFileSync(`${out}/pdf-lib.d.ts`, `export { PDFArray, PDFDict, PDFDocument, PDFName, PDFNumber, PDFRawStream, PDFRef, PDFStream, PDFString, PDFHexString, PDFContentStream, decodePDFRawStream } from 'pdf-lib';\nexport { Font as StandardFontMetrics, Encodings as StandardEncodings } from '@pdf-lib/standard-fonts';\n`);
fs.writeFileSync(`${out}/unpdf.d.ts`, `export { extractText, getDocumentProxy } from 'unpdf';\n`);
// 한글 CMap: 이름 → base64 (bcmap 형식, 원본 그대로)
// pdfjs-dist는 데이터 출처로만 쓰므로 의존성에 넣지 않는다 (캔버스 바이너리 등 ~70MB).
// 패키지 파일(tarball)만 임시 폴더에 받아 cmaps/만 꺼낸다 — node_modules는 건드리지 않음
const PDFJS = 'pdfjs-dist@6.1.200';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pacto-cmaps-'));
execSync(`npm pack ${PDFJS} --silent --pack-destination "${tmp}"`, { stdio: ['ignore', 'ignore', 'inherit'] });
const tgz = fs.readdirSync(tmp).find((f) => f.endsWith('.tgz'));
execSync(`tar -xzf "${tgz}" package/cmaps package/package.json`, { cwd: tmp });
const cmapDir = path.join(tmp, 'package/cmaps');
const pdfjsVersion = JSON.parse(fs.readFileSync(path.join(tmp, 'package/package.json'), 'utf8')).version;
const names = fs.readdirSync(cmapDir).filter((f) => /^(KSC|UniKS|Adobe-Korea1)[\w-]*\.bcmap$/.test(f)).sort();
const entries = names.map((f) => `  ${JSON.stringify(f.replace(/\.bcmap$/, ''))}: ${JSON.stringify(fs.readFileSync(`${cmapDir}/${f}`).toString('base64'))},`);
fs.writeFileSync(
  `${out}/korean-cmaps.js`,
  `// pdfjs-dist@${pdfjsVersion} cmaps (Korean only) — generated by scripts/vendor-pdf.mjs. Do not edit.\n` +
    `// Copyright 1990-2009 Adobe Systems Incorporated. BSD-3-Clause (see pdfjs-dist/cmaps/LICENSE)\n` +
    `export const KOREAN_CMAPS = {\n${entries.join('\n')}\n};\n`,
);
fs.writeFileSync(`${out}/korean-cmaps.d.ts`, `export declare const KOREAN_CMAPS: Record<string, string>;\n`);
fs.rmSync(tmp, { recursive: true, force: true });
console.log('vendored', targets.map((t) => `${t.name}@${pkg(t.name)}`).join(', '), `+ ${names.length} Korean CMaps (${PDFJS})`);
