// Edge Function용 qpdf(WASM) 번들 — 암호가 걸린 PDF를 사용자가 입력한 비밀번호로 "서버 메모리에서만" 여는 용도
// - @neslinesli93/qpdf-wasm 0.3.0 (ISC, https://github.com/neslinesli93/qpdf-wasm)
//   안에 든 것: qpdf 12.2.0 (Apache-2.0, https://github.com/qpdf/qpdf) + zlib (Zlib) + libjpeg-turbo 2.1.1 (IJG·BSD-3)
// - 버전 고정: 패키지 tarball의 sha512 무결성 값을 아래에 적어 두고, 다르면 중단한다
// - Supabase 배포는 import한 파일만 올라가므로 wasm은 base64로 모듈 안에 넣는다 (qpdf-wasm.js)
// - Deno(Edge Runtime)에서 Node 전용 코드가 실행되지 않도록 process를 없는 것으로 묶는다 (fs·path 사용 안 함)
// 의존성(package.json)에는 넣지 않는다 — 다시 만들 때만 받는다: node scripts/vendor-qpdf.mjs
import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const SPEC = '@neslinesli93/qpdf-wasm@0.3.0';
const INTEGRITY = 'sha512-ObyTmabopTMwN6AGwrEkmDbdmM5wnwlRdn9jnJYQ2KbBUPdPDcfNf1QkcWFOVD+qIgSqILz9nK51e22T+x+gkQ==';
const QPDF_VERSION = '12.2.0';
const out = 'supabase/functions/_shared/vendor';

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pacto-qpdf-'));
execSync(`npm pack ${SPEC} --silent --pack-destination "${tmp}"`, { stdio: ['ignore', 'ignore', 'inherit'] });
const tgz = fs.readdirSync(tmp).find((f) => f.endsWith('.tgz'));
const integrity = `sha512-${crypto.createHash('sha512').update(fs.readFileSync(path.join(tmp, tgz))).digest('base64')}`;
if (integrity !== INTEGRITY) throw new Error(`integrity mismatch for ${SPEC}: ${integrity}`);
execSync(`tar -xzf "${tgz}" package/dist package/package.json`, { cwd: tmp });
const dist = path.join(tmp, 'package/dist');
const wasm = fs.readFileSync(path.join(dist, 'qpdf.wasm'));
if (!wasm.includes(Buffer.from(QPDF_VERSION))) throw new Error(`qpdf ${QPDF_VERSION} not found in wasm`);

await build({
  entryPoints: [path.join(dist, 'qpdf.js')],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  minify: true,
  legalComments: 'eof',
  define: { process: 'undefined' },
  external: ['fs', 'path', 'crypto', 'module', 'url'],
  outfile: `${out}/qpdf.js`,
  banner: { js: `// ${SPEC} (ISC) — qpdf ${QPDF_VERSION} (Apache-2.0) + zlib + libjpeg-turbo. generated by scripts/vendor-qpdf.mjs. Do not edit.` },
  logLevel: 'warning',
});
// qpdf 메시지가 콘솔(=서버 로그)로 나가지 않게 막는다 — 이 빌드는 print/printErr 옵션 대신 console을 직접 쓴다.
// 대신 globalThis.__pactoQpdfSink(있을 때만)로 넘긴다: pdfDecrypt.ts가 동기 callMain 동안에만 지역 배열로 받고 바로 해제한다 (로그 출력 없음).
// 콘솔 호출이 늘거나 줄면 중단 (빌드가 바뀐 것)
{
  const file = `${out}/qpdf.js`;
  let code = fs.readFileSync(file, 'utf8');
  const hits = (code.match(/console\.(log|error|warn|info|debug)/g) ?? []).length;
  if (hits !== 2 || !code.includes('console.log.bind(console)') || !code.includes('console.error.bind(console)')) throw new Error(`unexpected console usage in qpdf bundle (${hits})`);
  const sink = '((...a)=>{const s=globalThis.__pactoQpdfSink;if(typeof s==="function")s(a.join(" "))})';
  code = code.replace('console.log.bind(console)', sink).replace('console.error.bind(console)', sink);
  if (/console\./.test(code)) throw new Error('console still referenced');
  fs.writeFileSync(file, code);
}
fs.writeFileSync(`${out}/qpdf.d.ts`, `/** emscripten 모듈 팩토리 (qpdf CLI) */\ndeclare const createModule: (opts: Record<string, unknown>) => Promise<{ FS: { writeFile(p: string, d: Uint8Array): void; readFile(p: string): Uint8Array; unlink(p: string): void }; callMain(args: string[]): number }>;\nexport default createModule;\n`);
fs.writeFileSync(
  `${out}/qpdf-wasm.js`,
  `// qpdf.wasm (qpdf ${QPDF_VERSION}) from ${SPEC} — base64. generated by scripts/vendor-qpdf.mjs. Do not edit.\n` +
    `export const QPDF_VERSION = ${JSON.stringify(QPDF_VERSION)};\nexport const QPDF_WASM_BASE64 = ${JSON.stringify(wasm.toString('base64'))};\n`,
);
fs.writeFileSync(`${out}/qpdf-wasm.d.ts`, `export declare const QPDF_VERSION: string;\nexport declare const QPDF_WASM_BASE64: string;\n`);
fs.rmSync(tmp, { recursive: true, force: true });
console.log(`vendored ${SPEC} (qpdf ${QPDF_VERSION}), wasm ${(wasm.length / 1024).toFixed(0)} KB`);
