// Edge Function용 이미지 코덱 번들 (버전 고정, 외부 네트워크 없이 배포·로컬 실행이 같도록) — 사진 계약서 보호본 생성
// - jpeg-js 0.4.4 (BSD-3-Clause, https://github.com/jpeg-js/jpeg-js): JPEG 해석·저장 — 순수 JS
// - fast-png 6.2.0 (MIT, https://github.com/image-js/fast-png, 의존: iobuffer MIT · pako MIT/Zlib): PNG 해석
// - @jsquash/jpeg 1.6.0 (Apache-2.0, https://github.com/jamsinclair/jSquash) 의 mozjpeg 해석기 WASM (mozjpeg: IJG·BSD-3·zlib 라이선스)
//   JPEG 해석만 WASM으로 (순수 JS보다 약 5배 빠름 — Edge CPU 한도 안에 들기 위해). 저장은 jpeg-js (mozjpeg 저장은 최적화 때문에 더 느렸음)
//   WASM 바이너리는 모듈 안에 base64로 넣는다 (Supabase 배포는 import한 파일만 올라감)
// 왜 vendor인가: Supabase Edge Runtime에는 sharp·canvas 같은 네이티브 모듈이 없고, 배포는 import한 파일만 올라간다.
//   jpeg-js는 Node의 Buffer를 쓰므로 Uint8Array로 대신하는 작은 shim을 넣는다 (Deno에서 node:buffer를 불러오지 않도록).
// 다시 만들기: node scripts/vendor-image.mjs
import { build } from 'esbuild';
import fs from 'node:fs';

const out = 'supabase/functions/_shared/vendor';
const pkg = (name) => JSON.parse(fs.readFileSync(`node_modules/${name}/package.json`, 'utf8')).version;
const shim = 'node_modules/.cache/pacto-buffer-shim.js';
fs.mkdirSync('node_modules/.cache', { recursive: true });
fs.writeFileSync(shim, 'export const Buffer = { from: (a) => Uint8Array.from(a), alloc: (n) => new Uint8Array(n), isBuffer: () => false };\n');
const decWasm = fs.readFileSync('node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm').toString('base64');
await build({
  stdin: {
    contents: `
export { encode as encodeJpeg, decode as decodeJpeg } from "jpeg-js";
export { decode as decodePng } from "fast-png";
// PDF 스캔 페이지의 Flate 이미지 풀기 — fast-png가 이미 쓰는 pako (추가 라이브러리 아님)
export { inflate } from "./node_modules/fast-png/node_modules/pako/dist/pako.esm.mjs";
import decodeWasm, { init as initDec } from "@jsquash/jpeg/decode.js";
// Deno에는 ImageData가 없다 — 해석기가 결과를 담을 최소한의 형태만
globalThis.ImageData ??= class ImageData { constructor(data, width, height) { this.data = data; this.width = width; this.height = height; } };
const DEC_WASM = "${decWasm}";
let ready = null;
/** mozjpeg WASM으로 JPEG 해석 → RGBA */
export async function decodeJpegFast(bytes) {
  ready ??= WebAssembly.compile(Uint8Array.from(atob(DEC_WASM), (c) => c.charCodeAt(0))).then((m) => initDec(m));
  await ready;
  const img = await decodeWasm(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));
  return { width: img.width, height: img.height, data: new Uint8Array(img.data.buffer, img.data.byteOffset, img.data.byteLength) };
}
`,
    resolveDir: process.cwd(),
    loader: 'js',
  },
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  mainFields: ['module', 'main'],
  inject: [shim],
  // jest(CommonJS 변환)에서도 불러올 수 있게 import.meta를 쓰지 않는다 (WASM은 위에서 직접 넣으므로 경로가 필요 없음)
  define: { 'import.meta.url': '"file:///vendor/imagecodec.js"' },
  minify: true,
  legalComments: 'eof',
  outfile: `${out}/imagecodec.js`,
  banner: { js: `// jpeg-js@${pkg('jpeg-js')} (BSD-3-Clause) + fast-png@${pkg('fast-png')} (MIT) + @jsquash/jpeg@${pkg('@jsquash/jpeg')} mozjpeg decoder (Apache-2.0 / IJG·BSD-3·zlib) — generated by scripts/vendor-image.mjs. Do not edit.` },
  logLevel: 'warning',
});
fs.writeFileSync(
  `${out}/imagecodec.d.ts`,
  `export interface RawImage { width: number; height: number; data: Uint8Array }
export declare function decodeJpeg(bytes: Uint8Array, opts?: { useTArray?: boolean; formatAsRGBA?: boolean; maxMemoryUsageInMB?: number; maxResolutionInMP?: number }): RawImage;
export declare function encodeJpeg(image: RawImage, quality?: number): { data: Uint8Array; width: number; height: number };
export declare function decodeJpegFast(bytes: Uint8Array): Promise<RawImage>;
export declare function inflate(bytes: Uint8Array): Uint8Array;
export declare function decodePng(bytes: Uint8Array): { width: number; height: number; channels: number; depth: number; data: Uint8Array | Uint16Array; palette?: number[][] };
`,
);
console.log('vendored', `jpeg-js@${pkg('jpeg-js')}`, `fast-png@${pkg('fast-png')}`, `@jsquash/jpeg@${pkg('@jsquash/jpeg')} (decoder wasm)`);
