// 앱 내 계약서 뷰어(WebView)용 pdf.js 번들 — 버전 고정, 앱에 포함 (CDN 사용 안 함)
// - pdfjs-dist 5.4.624 (Apache-2.0, https://github.com/mozilla/pdf.js) legacy 빌드: 화면 그리기 + 작업자(worker)
// - wasm: openjpeg(JPEG2000, BSD-2-Clause) · jbig2(흑백 스캔, PDFium BSD-3-Clause) — 스캔 원본 PDF 표시용
// - 한글 CMap: 서버와 같은 데이터(supabase/functions/_shared/vendor/korean-cmaps.js, Adobe BSD-3-Clause)
// 결과: src/features/viewer/viewerScript.generated.js (WebView HTML에 넣는 스크립트 한 덩어리)
// 다시 만들기: node scripts/vendor-viewer.mjs  (npm에서 pdfjs-dist 묶음을 내려받는다 — 의존성에는 넣지 않음)
import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const PDFJS = 'pdfjs-dist@5.4.624';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pacto-viewer-'));
execSync(`npm pack ${PDFJS} --silent`, { cwd: tmp, stdio: ['ignore', 'pipe', 'inherit'] });
const tgz = fs.readdirSync(tmp).find((f) => f.endsWith('.tgz'));
execSync(`tar xzf ${tgz}`, { cwd: tmp });
const pkg = path.join(tmp, 'package');
const version = JSON.parse(fs.readFileSync(path.join(pkg, 'package.json'), 'utf8')).version;

// 작업자: ESM → 일반 스크립트 (Blob Worker로 실행, 끝의 export 제거)
const worker = await build({
  entryPoints: [path.join(pkg, 'legacy/build/pdf.worker.min.mjs')],
  bundle: true,
  format: 'iife',
  minify: true,
  write: false,
  platform: 'browser',
  define: { 'import.meta.url': '"about:blank"' },
  logLevel: 'error',
});
const WORKER_SOURCE = worker.outputFiles[0].text;
const WASM_FILES = Object.fromEntries(['openjpeg.wasm', 'jbig2.wasm'].map((f) => [f, fs.readFileSync(path.join(pkg, 'wasm', f)).toString('base64')]));

const main = await build({
  entryPoints: ['scripts/viewer/viewer.js'],
  bundle: true,
  format: 'iife',
  minify: true,
  write: false,
  platform: 'browser',
  target: ['chrome80', 'safari15'],
  define: { 'import.meta.url': '"about:blank"' },
  legalComments: 'eof',
  logLevel: 'error',
  plugins: [
    {
      name: 'pacto-viewer',
      setup(b) {
        b.onResolve({ filter: /^pdfjs-legacy$/ }, () => ({ path: path.join(pkg, 'legacy/build/pdf.min.mjs') }));
        b.onResolve({ filter: /^pacto-viewer-embedded$/ }, () => ({ path: 'embedded', namespace: 'pacto' }));
        b.onLoad({ filter: /.*/, namespace: 'pacto' }, () => ({
          contents: `export const WORKER_SOURCE = ${JSON.stringify(WORKER_SOURCE)};\nexport const WASM_FILES = ${JSON.stringify(WASM_FILES)};`,
          loader: 'js',
        }));
      },
    },
  ],
});
// HTML <script> 안에 넣으므로 닫는 태그처럼 보이는 글자를 바꾼다 (자바스크립트 의미는 같음)
const script = main.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const out = 'src/features/viewer';
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(
  `${out}/viewerScript.generated.js`,
  `// pdfjs-dist@${version} (Apache-2.0) legacy build + openjpeg(BSD-2) · jbig2(BSD-3) wasm + Korean CMaps (Adobe BSD-3) + scripts/viewer/viewer.js\n` +
    `// generated by scripts/vendor-viewer.mjs. Do not edit.\n` +
    `export const PDFJS_VERSION = ${JSON.stringify(version)};\nexport const VIEWER_SCRIPT = ${JSON.stringify(script)};\n`,
);
fs.writeFileSync(`${out}/viewerScript.generated.d.ts`, 'export declare const PDFJS_VERSION: string;\nexport declare const VIEWER_SCRIPT: string;\n');
// 라이선스 원문 보관 (Apache-2.0 고지 · wasm 라이선스)
const lic = 'third_party/viewer';
fs.mkdirSync(lic, { recursive: true });
fs.copyFileSync(path.join(pkg, 'LICENSE'), `${lic}/pdfjs-dist-LICENSE`);
for (const f of fs.readdirSync(path.join(pkg, 'wasm')).filter((x) => /^LICENSE_(OPENJPEG|PDFJS_OPENJPEG|JBIG2|PDFJS_JBIG2)$/.test(x))) fs.copyFileSync(path.join(pkg, 'wasm', f), `${lic}/${f}`);
fs.rmSync(tmp, { recursive: true, force: true });
console.log(`viewer script: pdfjs-dist@${version}, ${(script.length / 1024 / 1024).toFixed(2)} MB`);
